### ISSUE TITLE
HOw ThE FuCk cAn i uSe thIs cOde 

### ISSUE THREAD

**Issue by NeutronO** [jexroid/Lexroid#2]
tell me

**Comment by NeutronO** [comment]
oi

**Comment by jexroid** [comment]
you can simply use the code by following steps : 
clone the repository then change the directory to it using :
```yaml
cd lexroid 
```
give the execution permission using :
```yaml
chmod +x ./lexroid.sh
```
the type following command:

```yaml
bash lexroid.sh <domain>
```
